//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KancolleVV.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"DefaultEndpointsProtocol=https;AccountName=kancollevdb;AccountKey=VwjCnYOYYL/5mF+CKYu4evctVmr6tMrjI4/d8gIPZt+JCGhUyDzhXqZB8rBj9U6xdOk+YlFrVuD7ZdmUkaWKIA==;BlobEndpoint=https://kancollevdb.blob.core.windows.net/;TableEndpoint=https://kancollevdb.table.core.windows.net/;QueueEndpoint=https://kancollevdb.queue.core.windows.net/;FileEndpoint=https://kancollevdb.file.core.windows.net/")]
        public string kancollevdbString {
            get {
                return ((string)(this["kancollevdbString"]));
            }
        }
    }
}
